name: Singularity Build (native)
on:
  push:
    branches:
      - main

jobs:
  changes:
    name: "Changed Singularity Recipes"
    runs-on: ubuntu-latest
    outputs:
      changed_file: ${{ steps.files.outputs.added_modified }}
    steps:
      - id: files
        uses: jitterbit/get-changed-files@b17fbb00bdc0c0f63fcf166580804b4d2cdc2a42
        with:
          format: 'json'

  build-test-containers:
    needs: [changes]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        changed_file: ${{ fromJson(needs.changes.outputs.changed_file) }}

    name: Check ${{ matrix.changed_file }}
    steps:
      - name: Continue if Singularity Recipe
        run: |
          if [[ "${{ matrix.changed_file }}" = *.def ]]; then
            echo "keepgoing=true" >> $GITHUB_ENV
          fi

      - name: Set up Go
        if: env.keepgoing == 'true'
        uses: actions/setup-go@v5

      - name: Install Dependencies
        if: env.keepgoing == 'true'
        run: |
          sudo apt-get update && sudo apt-get install -y \
            build-essential \
            libssl-dev \
            uuid-dev \
            libgpgme11-dev \
            squashfs-tools \
            libseccomp-dev \
            pkg-config \
            autoconf \
            automake \
            cryptsetup \
            fuse2fs \
            git \
            fuse \
            libfuse-dev \
            libtool \
            runc \
            squashfs-tools-ng \
            uidmap \
            wget \
            zlib1g-dev \
            libsubid-dev

      - name: Install Singularity
        if: env.keepgoing == 'true'
        env:
          SINGULARITY_VERSION: 4.3.0
          GOPATH: /tmp/go
        run: |
          mkdir -p $GOPATH
          sudo mkdir -p /usr/local/var/singularity/mnt
          mkdir -p $GOPATH/src/github.com/sylabs
          cd $GOPATH/src/github.com/sylabs
          wget -qO- https://github.com/sylabs/singularity/releases/download/v${SINGULARITY_VERSION}/singularity-ce-${SINGULARITY_VERSION}.tar.gz | tar xzv
          cd singularity-ce-${SINGULARITY_VERSION}
          ./mconfig -p /usr/local
          make -C builddir
          sudo make -C builddir install

      - name: Check out code for the container build
        if: env.keepgoing == 'true'
        uses: actions/checkout@v4

      - name: Build Container
        if: env.keepgoing == 'true'
        env:
          recipe: ${{ matrix.changed_file }}
        run: |
          if [ -f "${recipe}" ]; then
            sudo -E singularity build container.sif ${recipe}
            tag=$(git describe --tags --always)
            tag=${tag}-x86
            echo "Tag is ${tag}."
            echo "tag=${tag}" >> $GITHUB_ENV
          else
            echo "${recipe} is not found."
            exit 1
          fi

      - name: Login and Deploy Container
        if: github.event_name != 'pull_request' && env.keepgoing == 'true'
        env:
          GHCR_USERNAME: ${{ secrets.GHCR_USERNAME }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo $GITHUB_TOKEN | singularity registry login -u $GHCR_USERNAME --password-stdin oras://ghcr.io
          singularity push container.sif oras://ghcr.io/${GITHUB_REPOSITORY}:${tag}

      - name: Test Container
        if: env.keepgoing == 'true'
        run: |
          singularity pull oras://ghcr.io/${GITHUB_REPOSITORY}:${tag}
          singularity exec ${tag}.sif echo "Container ${tag} executed successfully!"