name: Build and Push Singularity Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: 'false'

      - name: Singularity setup
        uses: singularityhub/install-singularity@main

      - name: Import and Verify Singularity key
        env:
          KEY_B64: ${{ secrets.SIGNING_KEY }}
          KEY_PASS: ${{ secrets.KEY_PASSPHRASE }}
        run: |
          # Decode key and verify format
          echo "$KEY_B64" | base64 -d > private.asc
          echo "=== Key File Header ==="
          head -n 1 private.asc  # Should show "-----BEGIN PGP PRIVATE KEY BLOCK-----"
          
          # Import key with passphrase validation
          echo "=== Key Import ==="
          echo "$KEY_PASS" | singularity key import private.asc 2>&1 | tee import.log
          
          # Verify successful import
          echo "=== Imported Keys ==="
          singularity key list
          
      - name: Build Singularity Image
        run: |
            sudo -E singularity build hello.sif hello.def


      - name: Sign the image
        run: |
           echo "${{ secrets.KEY_PASSPHRASE }}" | singularity sign --keyidx 0 hello.sif

      - name: Configure ORAS Remote
        run: |
          # Add a new remote named 'ghcr' pointing to oras://ghcr.io
          singularity remote add --no-login ghcr oras://ghcr.io

      - name: Login and Push to GitHub Registry
        env:
          IMAGE_NAME: romer8/test-singularity
          GHCR_USERNAME: ${{ github.actor }}
        run: |
          # Login to the 'ghcr' remote with your GitHub token
          echo "${{ secrets.GITHUB_TOKEN }}" | singularity remote login -u "${{ env.GHCR_USERNAME }}" --password-stdin ghcr

          # Push the image to the 'ghcr' remote with the desired tag
          singularity push hello.sif oras://ghcr.io/${{ env.IMAGE_NAME }}:latest_x86


      - name: Test the image
        run: |
          singularity pull oras://ghcr.io/romer8/test-singularity:hello
          singularity run test-singularity.sif